[package]
name = "nbs_tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
crossterm = "0.25"
nom = "7.1.3"
symphonia-format-ogg = "0.5.3"
rodio = "0.17.1"