[package]
name = "nbs_tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
ratatui = "0.20.1"
bitflags = "2.3.3"
nom = "7.1.3"
symphonia-format-ogg = "0.5.3"
rodio = "0.17.1"